### ISSUE TITLE
its not working any more...please check

### ISSUE THREAD

**Issue by rudrab** [cphyc/fortran-syntax#2]
Hi,

I have just found this excellent project. Though I have problem in installing. 
```
 sudo  pip3 install fortran-linter
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting fortran-linter
  Using cached https://files.pythonhosted.org/packages/fe/ef/9112b8c5aa7e3a6d1e6b924ddd01892797bf79beb3fb53466e9cdbf49529/fortran_linter-1.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4725p54t/fortran-linter/setup.py", line 7, in <module>
        long_description = open(README).read()
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-4725p54t/fortran-linter/Readme.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-4725p54t/fortran-linter/
```
Then, with `git clone; setup` I have installed it in my userspace. now:

```
~/.local/bin/fortran-linter -h
Traceback (most recent call last):
  File "/home/rudra/.local/bin/fortran-linter", line 11, in <module>
    load_entry_point('fortran-linter==1.0.1', 'console_scripts', 'fortran-linter')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named fortran_linter.cli

```

**Comment by cphyc** [comment]
Hi rudrab,

I had not updated the pip package (this is now done, version 1.0.4).
Please also note that from what I can see, you're probably using both python2 and python3 at the same time, which may cause some troubles in the installation problem.

**Comment by cphyc** [comment]
I think this is fixed. Closing for now.

**Comment by rudrab** [comment]
Thnaks
