### ISSUE TITLE
Does not run with Intel Python distribution on Windows

### ISSUE THREAD

**Issue by Beliavsky** [cphyc/fortran-syntax#4]
Thanks for creating this. I have the Intel Python 3 distribution installed on Windows, and I installed fortran-linter using pip. Running it, I get this:

c:\fortran\2015>fortran-linter reg_stats.f90 --syntax-only
Traceback (most recent call last):
  File "c:\intelpython3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\intelpython3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\intelpython3\Scripts\fortran-linter.exe\__main__.py", line 4, in <module>
  File "c:\intelpython3\lib\site-packages\fortran_linter\__init__.py", line 1, in <module>
    from .main import FortranRules, LineChecker  # noqa: F401
  File "c:\intelpython3\lib\site-packages\fortran_linter\main.py", line 7, in <module>
    def to_lowercase(line: str, match: re.Match):
AttributeError: module 're' has no attribute 'Match'

**Comment by cphyc** [comment]
What is the python version you are running with?

**Comment by Beliavsky** [comment]
Python 3.6.9 from Intel

**Comment by cphyc** [comment]
Should be fixed as of 60080449d2d7ea7b25b1a933ddcf0fada11c2f1c.

**Comment by cphyc** [comment]
Closing this for now, please re-open if the problem persists. Note that I haven't update to pypi package.
